// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Org struct {
	ID           int32
	Name         string
	CreatedAt    pgtype.Timestamptz
	Role         string
	PasswordHash string
}

type Request struct {
	ID         int32
	Name       string
	Sequence   string
	Age        int16
	HospitalID int32
	LabID      int32
	Status     string
	Report     *string
}

type Session struct {
	ID        string
	OrgID     int32
	ExpiresAt time.Time
}
